### ISSUE TITLE
Make comment frontmatter work

### ISSUE THREAD

**Issue by ghost** [TechnologyAdvice/technologyadvice.github.io#18]
We want `comments: true` or `comments: false` in the front-matter of a post to quickly turn on and off Disqus comments. You can see a working example of how to do this here: https://github.com/jhabdas/habd.as

**EDIT** In doing so we should remove anything tagged `disqus` for clarity and DRYness.

**Comment by dvdzkwsk** [comment]
:+1:

**Comment by jhabdas** [comment]
Note, issue opened when comments stopped working earlier. They're working now, so this issue may only require a simple confirmation of existing functionality.

**Comment by jhabdas** [comment]
Wait, I lied. Submitting PR to restore comments for all posts until issue resolved.
